import pytest
import os
import shutil
import glob
import re
import numpy as np
from typing import Callable
from classification import ClassifierParams
from receiver import Receiver


def pytest_addoption(parser):
    parser.addoption(
        "--persist-iq",
        action="store_true",
        default=False,
        help="Persist dynamically generated .iq test signals to test_signals/debug/"
    )
    parser.addoption(
        "--plot-iq",
        action="store_true",
        default=False,
        help="Generate spectrogram PNG plots of dynamically generated .iq test signals in test_signals/debug/"
    )
    parser.addoption(
        "--persist-wav",
        action="store_true",
        default=False,
        help="Persist demodulated .wav files generated by tests to test_signals/debug/"
    )
    parser.addoption(
        "--run-busy-net",
        action="store_true",
        default=False,
        help="run tests that require busy/live network access",
    )

def plot_spectrogram(iq_filepath, png_filepath, sample_rate=1.0e6):
    """Generates a spectrogram PNG plot of the IQ data, handling missing dependencies gracefully."""
    try:
        import matplotlib
        matplotlib.use('Agg')  # Headless mode
        import matplotlib.pyplot as plt
        import scipy.signal as signal
    except ImportError as e:
        print(f"\n[Warning] Could not import matplotlib or scipy. Spectrogram plot skipped. Error: {e}")
        return

    try:
        # Load IQ data
        data = np.fromfile(iq_filepath, dtype=np.complex64)
        if len(data) < 16:
            print(f"\n[Warning] IQ file {iq_filepath} is too short ({len(data)} samples) for spectrogram. Skipping plot.")
            return

        # Compute spectrogram parameters dynamically to handle short files safely
        nperseg = min(1024, len(data))
        noverlap = nperseg // 2

        # Compute spectrogram. Since IQ data is complex, return_onesided must be False
        f, t, Sxx = signal.spectrogram(
            data,
            fs=sample_rate,
            nperseg=nperseg,
            noverlap=noverlap,
            return_onesided=False
        )

        # Shift frequency zero component to center
        f = np.fft.fftshift(f)
        Sxx = np.fft.fftshift(Sxx, axes=0)

        # Convert power to dB, clamping low values to avoid log of 0
        Sxx_db = 10 * np.log10(np.abs(Sxx) + 1e-15)

        # Plot the spectrogram
        plt.figure(figsize=(10, 6))
        plt.pcolormesh(t, f / 1e3, Sxx_db, shading='gouraud', cmap='viridis')
        plt.colorbar(label='Intensity (dB)')
        plt.title(f"Spectrogram of {os.path.basename(iq_filepath)}")
        plt.xlabel("Time (s)")
        plt.ylabel("Frequency Offset (kHz)")
        plt.tight_layout()
        plt.savefig(png_filepath, dpi=150)
        plt.close()
        print(f"\n[Debug] Generated spectrogram plot: {png_filepath}")
    except Exception as e:
        print(f"\n[Warning] Failed to generate spectrogram plot for {iq_filepath}: {e}")

@pytest.fixture(autouse=True)
def handle_debug_iq(request, tmp_path):
    """Autouse fixture to intercept, persist, and plot dynamically generated IQ signals."""
    yield

    persist_iq = request.config.getoption("--persist-iq")
    plot_iq = request.config.getoption("--plot-iq")

    if not (persist_iq or plot_iq):
        return

    # Find all .iq files in tmp_path recursively
    iq_files = glob.glob(os.path.join(str(tmp_path), "**", "*.iq"), recursive=True)
    if not iq_files:
        return

    # Determine repo root and debug folder path
    repo_root = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
    debug_dir = os.path.join(repo_root, "test_signals", "debug")
    os.makedirs(debug_dir, exist_ok=True)

    # Sanitize the test name for use as part of a filename
    sanitized_test_name = re.sub(r'[^a-zA-Z0-9_\.-]', '_', request.node.name)

    for iq_file in iq_files:
        base_name = os.path.basename(iq_file)
        dest_iq_name = f"{sanitized_test_name}_{base_name}"
        dest_iq_path = os.path.join(debug_dir, dest_iq_name)

        if persist_iq:
            try:
                shutil.copy2(iq_file, dest_iq_path)
                print(f"\n[Debug] Persisted IQ signal: {dest_iq_path}")
            except Exception as e:
                print(f"\n[Warning] Failed to persist IQ signal from {iq_file} to {dest_iq_path}: {e}")

        if plot_iq:
            # Determine PNG destination path
            root_name, _ = os.path.splitext(base_name)
            dest_png_name = f"{sanitized_test_name}_{root_name}.png"
            dest_png_path = os.path.join(debug_dir, dest_png_name)
            plot_spectrogram(iq_file, dest_png_path)


@pytest.fixture
def test_wav_dir(tmp_path, request):
    """Fixture to provide a clean temporary directory for WAV recordings."""
    wav_dir = tmp_path / "wav"
    os.makedirs(wav_dir, exist_ok=True)
    yield str(wav_dir)

    persist_wav = request.config.getoption("--persist-wav")
    if persist_wav:
        # Find all .wav files in wav_dir
        wav_files = glob.glob(os.path.join(str(wav_dir), "*.wav"))
        if wav_files:
            # Determine repo root and debug folder path
            repo_root = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
            debug_dir = os.path.join(repo_root, "test_signals", "debug")
            os.makedirs(debug_dir, exist_ok=True)

            # Sanitize the test name for use as part of a filename
            sanitized_test_name = re.sub(r'[^a-zA-Z0-9_\.-]', '_', request.node.name)

            for wav_file in wav_files:
                base_name = os.path.basename(wav_file)
                dest_wav_name = f"{sanitized_test_name}_{base_name}"
                dest_wav_path = os.path.join(debug_dir, dest_wav_name)
                try:
                    shutil.copy2(wav_file, dest_wav_path)
                    print(f"\n[Debug] Persisted WAV file: {dest_wav_path}")
                except Exception as e:
                    print(f"\n[Warning] Failed to persist WAV file from {wav_file} to {dest_wav_path}: {e}")

    # Cleanup after test runs
    if wav_dir.exists():
        shutil.rmtree(wav_dir)

@pytest.fixture
def mock_notify_scanner():
    """No-op callback for scanner notifications."""
    async def _noop(msg):
        pass
    return _noop

@pytest.fixture
def mock_get_priority_info():
    """Stub callback for priority information."""
    def _stub(freq):
        return None, False
    return _stub

@pytest.fixture
def receiver_factory(test_wav_dir, mock_notify_scanner, mock_get_priority_info):
    """Factory fixture to instantiate Receiver with a mock file source."""
    created_receivers = []

    def _create_receiver(
        source_file: str,
        sample_rate: int = 1_000_000,
        num_demod: int = 1,
        type_demod: int = 0,  # 0 = NBFM
        audio_bps: int = 16,
        min_recording: float = 0.5,
        center_freq: int = 144_000_000,
        record: bool = True,
        play: bool = False,
        agc: bool = False,
        file_metadata: list[str] | None = None,
        get_ctcss_info: Callable[[float], list[float]] | None = None,
        max_ctcss_tones: int = 3
    ) -> Receiver:
        classifier_params = ClassifierParams(
            wanted={'V': False, 'D': False, 'S': False},
            model_file_name=None
        )

        rx = Receiver(
            ask_samp_rate=sample_rate,
            num_demod=num_demod,
            type_demod=type_demod,
            hw_args="",
            freq_correction=0,
            record=record,
            play=play,
            audio_bps=audio_bps,
            min_recording=min_recording,
            classifier_params=classifier_params,
            notify_scanner=mock_notify_scanner,
            agc=agc,
            file_metadata=file_metadata,
            get_priority_info=mock_get_priority_info,
            get_ctcss_info=get_ctcss_info,
            max_ctcss_tones=max_ctcss_tones,
            source_type="file",
            source_file=source_file,
            wav_dir=test_wav_dir,
            center_freq=center_freq
        )
        created_receivers.append(rx)
        return rx


    yield _create_receiver

    for rx in created_receivers:
        try:
            rx.stop()
            rx.wait()
        except Exception:
            pass

@pytest.fixture
def run_busy_net(request):
    if not request.config.getoption("--run-busy-net"):
        pytest.skip("need --run-busy-net option to run")
